// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: rcent.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RcenterCmd int32

const (
	RcenterCmd_RcenterUnused       RcenterCmd = 0
	RcenterCmd_UpdateOnlinePlayNum RcenterCmd = 2
	RcenterCmd_UpdateRoomList      RcenterCmd = 3
)

// Enum value maps for RcenterCmd.
var (
	RcenterCmd_name = map[int32]string{
		0: "RcenterUnused",
		2: "UpdateOnlinePlayNum",
		3: "UpdateRoomList",
	}
	RcenterCmd_value = map[string]int32{
		"RcenterUnused":       0,
		"UpdateOnlinePlayNum": 2,
		"UpdateRoomList":      3,
	}
)

func (x RcenterCmd) Enum() *RcenterCmd {
	p := new(RcenterCmd)
	*p = x
	return p
}

func (x RcenterCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RcenterCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_rcent_proto_enumTypes[0].Descriptor()
}

func (RcenterCmd) Type() protoreflect.EnumType {
	return &file_rcent_proto_enumTypes[0]
}

func (x RcenterCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RcenterCmd.Descriptor instead.
func (RcenterCmd) EnumDescriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{0}
}

type ReqGetRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
}

func (x *ReqGetRoom) Reset() {
	*x = ReqGetRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetRoom) ProtoMessage() {}

func (x *ReqGetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetRoom.ProtoReflect.Descriptor instead.
func (*ReqGetRoom) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RetGetRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Addr   string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *RetGetRoom) Reset() {
	*x = RetGetRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetGetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetGetRoom) ProtoMessage() {}

func (x *RetGetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetGetRoom.ProtoReflect.Descriptor instead.
func (*RetGetRoom) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{1}
}

func (x *RetGetRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RetGetRoom) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ReqDelRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
}

func (x *ReqDelRoom) Reset() {
	*x = ReqDelRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDelRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDelRoom) ProtoMessage() {}

func (x *ReqDelRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDelRoom.ProtoReflect.Descriptor instead.
func (*ReqDelRoom) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{2}
}

func (x *ReqDelRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RetDelRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetDelRoom) Reset() {
	*x = RetDelRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetDelRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetDelRoom) ProtoMessage() {}

func (x *RetDelRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetDelRoom.ProtoReflect.Descriptor instead.
func (*RetDelRoom) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{3}
}

type ReqGetRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetRoomList) Reset() {
	*x = ReqGetRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetRoomList) ProtoMessage() {}

func (x *ReqGetRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetRoomList.ProtoReflect.Descriptor instead.
func (*ReqGetRoomList) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{4}
}

type RetGetRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomIds []string `protobuf:"bytes,1,rep,name=RoomIds,proto3" json:"RoomIds,omitempty"`
}

func (x *RetGetRoomList) Reset() {
	*x = RetGetRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetGetRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetGetRoomList) ProtoMessage() {}

func (x *RetGetRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetGetRoomList.ProtoReflect.Descriptor instead.
func (*RetGetRoomList) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{5}
}

func (x *RetGetRoomList) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type ReqUpdateRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomIds []string `protobuf:"bytes,1,rep,name=RoomIds,proto3" json:"RoomIds,omitempty"`
	Nums    []int32  `protobuf:"varint,2,rep,packed,name=Nums,proto3" json:"Nums,omitempty"`
}

func (x *ReqUpdateRoomList) Reset() {
	*x = ReqUpdateRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateRoomList) ProtoMessage() {}

func (x *ReqUpdateRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateRoomList.ProtoReflect.Descriptor instead.
func (*ReqUpdateRoomList) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{6}
}

func (x *ReqUpdateRoomList) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

func (x *ReqUpdateRoomList) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

type RetUpdateRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetUpdateRoomList) Reset() {
	*x = RetUpdateRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetUpdateRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetUpdateRoomList) ProtoMessage() {}

func (x *RetUpdateRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetUpdateRoomList.ProtoReflect.Descriptor instead.
func (*RetUpdateRoomList) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{7}
}

type ReqGetToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ReqGetToken) Reset() {
	*x = ReqGetToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetToken) ProtoMessage() {}

func (x *ReqGetToken) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetToken.ProtoReflect.Descriptor instead.
func (*ReqGetToken) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{8}
}

func (x *ReqGetToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RetGetToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RetGetToken) Reset() {
	*x = RetGetToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetGetToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetGetToken) ProtoMessage() {}

func (x *RetGetToken) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetGetToken.ProtoReflect.Descriptor instead.
func (*RetGetToken) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{9}
}

func (x *RetGetToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReqRemovePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId string `protobuf:"bytes,1,opt,name=PlayId,proto3" json:"PlayId,omitempty"`
	RoomId string `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
}

func (x *ReqRemovePlayer) Reset() {
	*x = ReqRemovePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRemovePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRemovePlayer) ProtoMessage() {}

func (x *ReqRemovePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRemovePlayer.ProtoReflect.Descriptor instead.
func (*ReqRemovePlayer) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{10}
}

func (x *ReqRemovePlayer) GetPlayId() string {
	if x != nil {
		return x.PlayId
	}
	return ""
}

func (x *ReqRemovePlayer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RetRemovePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetRemovePlayer) Reset() {
	*x = RetRemovePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetRemovePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetRemovePlayer) ProtoMessage() {}

func (x *RetRemovePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_rcent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetRemovePlayer.ProtoReflect.Descriptor instead.
func (*RetRemovePlayer) Descriptor() ([]byte, []int) {
	return file_rcent_proto_rawDescGZIP(), []int{11}
}

var File_rcent_proto protoreflect.FileDescriptor

var file_rcent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x24, 0x0a,
	0x0a, 0x52, 0x65, 0x71, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6f,
	0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x73, 0x22,
	0x41, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x75,
	0x6d, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65,
	0x74, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x41, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2a, 0x4c, 0x0a, 0x0a, 0x52, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x43, 0x6d, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x6e,
	0x75, 0x73, 0x65, 0x64, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x10, 0x02, 0x12,
	0x12, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x10, 0x03, 0x32, 0xb2, 0x02, 0x0a, 0x07, 0x52, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f,
	0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x52, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x27, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x0b, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x0b, 0x2e, 0x52,
	0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x28, 0x01, 0x30, 0x01, 0x12, 0x27, 0x0a,
	0x07, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x71, 0x44, 0x65,
	0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x0b, 0x2e, 0x52, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x52, 0x6f,
	0x6f, 0x6d, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x52,
	0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x0c,
	0x2e, 0x52, 0x65, 0x74, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x10, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x6d, 0x61, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rcent_proto_rawDescOnce sync.Once
	file_rcent_proto_rawDescData = file_rcent_proto_rawDesc
)

func file_rcent_proto_rawDescGZIP() []byte {
	file_rcent_proto_rawDescOnce.Do(func() {
		file_rcent_proto_rawDescData = protoimpl.X.CompressGZIP(file_rcent_proto_rawDescData)
	})
	return file_rcent_proto_rawDescData
}

var file_rcent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rcent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rcent_proto_goTypes = []interface{}{
	(RcenterCmd)(0),           // 0: RcenterCmd
	(*ReqGetRoom)(nil),        // 1: ReqGetRoom
	(*RetGetRoom)(nil),        // 2: RetGetRoom
	(*ReqDelRoom)(nil),        // 3: ReqDelRoom
	(*RetDelRoom)(nil),        // 4: RetDelRoom
	(*ReqGetRoomList)(nil),    // 5: ReqGetRoomList
	(*RetGetRoomList)(nil),    // 6: RetGetRoomList
	(*ReqUpdateRoomList)(nil), // 7: ReqUpdateRoomList
	(*RetUpdateRoomList)(nil), // 8: RetUpdateRoomList
	(*ReqGetToken)(nil),       // 9: ReqGetToken
	(*RetGetToken)(nil),       // 10: RetGetToken
	(*ReqRemovePlayer)(nil),   // 11: ReqRemovePlayer
	(*RetRemovePlayer)(nil),   // 12: RetRemovePlayer
}
var file_rcent_proto_depIdxs = []int32{
	5,  // 0: RCenter.GetRoomList:input_type -> ReqGetRoomList
	1,  // 1: RCenter.GetRoom:input_type -> ReqGetRoom
	3,  // 2: RCenter.DelRoom:input_type -> ReqDelRoom
	7,  // 3: RCenter.UpdateRoomList:input_type -> ReqUpdateRoomList
	9,  // 4: RCenter.GetToken:input_type -> ReqGetToken
	11, // 5: RCenter.RemovePlayer:input_type -> ReqRemovePlayer
	6,  // 6: RCenter.GetRoomList:output_type -> RetGetRoomList
	2,  // 7: RCenter.GetRoom:output_type -> RetGetRoom
	4,  // 8: RCenter.DelRoom:output_type -> RetDelRoom
	8,  // 9: RCenter.UpdateRoomList:output_type -> RetUpdateRoomList
	10, // 10: RCenter.GetToken:output_type -> RetGetToken
	12, // 11: RCenter.RemovePlayer:output_type -> RetRemovePlayer
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rcent_proto_init() }
func file_rcent_proto_init() {
	if File_rcent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rcent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetGetRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDelRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetDelRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetGetRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetUpdateRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetGetToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRemovePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rcent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetRemovePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rcent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rcent_proto_goTypes,
		DependencyIndexes: file_rcent_proto_depIdxs,
		EnumInfos:         file_rcent_proto_enumTypes,
		MessageInfos:      file_rcent_proto_msgTypes,
	}.Build()
	File_rcent_proto = out.File
	file_rcent_proto_rawDesc = nil
	file_rcent_proto_goTypes = nil
	file_rcent_proto_depIdxs = nil
}
